// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3002' | (string & {});
};

export type AuditLogResponseDto = {
    /**
     * Unique identifier for the audit log
     */
    id: string;
    /**
     * Type of action performed
     */
    actionType: 'LOGIN' | 'LOGOUT' | 'LOGIN_FAILED' | 'PASSWORD_CHANGED' | 'PASSWORD_RESET' | 'CREATE' | 'UPDATE' | 'DELETE' | 'ROLE_CHANGED' | 'PERMISSION_CHANGED' | 'STATUS_CHANGED' | 'INVENTORY_ADJUSTED' | 'BATCH_ASSIGNED' | 'REPORT_EXPORTED' | 'DATA_EXPORTED' | 'SALE_CREATED' | 'SALE_UPDATED' | 'SALE_CANCELLED' | 'CONFIGURATION_CHANGED' | 'SYSTEM_ACTION' | 'USER_CREATED' | 'USER_UPDATED' | 'USER_DELETED' | 'USER_DEACTIVATED' | 'USER_ACTIVATED';
    /**
     * Type of entity affected
     */
    entityType: 'USER' | 'PRODUCT' | 'BATCH' | 'INVENTORY' | 'SALE' | 'CHECKOUT' | 'CART' | 'COOPERATIVE' | 'COOPERATIVE_MEMBER' | 'CUSTOMER' | 'REPORT' | 'SYSTEM' | 'CONFIGURATION' | 'AUTHENTICATION';
    /**
     * ID of the entity affected
     */
    entityId?: string;
    /**
     * Human-readable description of the action
     */
    description: string;
    /**
     * ID of user who performed the action
     */
    performedByUserId: string;
    /**
     * Name of user who performed the action
     */
    performedByUserName?: string;
    /**
     * Role of user who performed the action
     */
    performedByRole: 'user' | 'admin' | 'superadmin';
    /**
     * IP address from which action was performed
     */
    ipAddress?: string;
    /**
     * User agent string of the client
     */
    userAgent?: string;
    /**
     * Timestamp when action was performed
     */
    timestamp: string;
    /**
     * Additional metadata (before/after values, etc.)
     */
    metadata?: {
        [key: string]: unknown;
    };
};

export type RegisterUserDto = {
    [key: string]: unknown;
};

export type UserResponseDto = {
    /**
     * Unique identifier for the user
     */
    id: string;
    /**
     * Email address of the user
     */
    email: string;
    /**
     * Full name of the user
     */
    name: string;
    /**
     * User role/type
     */
    userType: 'user' | 'admin' | 'superadmin';
    /**
     * Phone number of the user
     */
    phoneNumber?: string;
    /**
     * User permissions
     */
    permissions?: string;
    /**
     * Whether the user must change their password on next login
     */
    mustChangePassword: boolean;
    /**
     * Remember token for authentication
     */
    rememberToken?: string;
    /**
     * User account status
     */
    status: 'active' | 'inactive' | 'suspended';
    /**
     * Date of birth
     */
    dob?: string;
    /**
     * Account creation date
     */
    createdAt: string;
    /**
     * Email verification date
     */
    emailVerifiedAt?: string;
    /**
     * Last update date
     */
    updatedAt: string;
};

export type AuthResponseDto = {
    /**
     * Response message
     */
    message: string;
    /**
     * User data
     */
    data: UserResponseDto;
};

export type ValidationErrorResponseDto = {
    /**
     * HTTP status code
     */
    statusCode: number;
    /**
     * Detailed validation errors
     */
    message: Array<Array<unknown>>;
    /**
     * Error type/reason
     */
    error: string;
};

export type ErrorResponseDto = {
    /**
     * HTTP status code
     */
    statusCode: number;
    /**
     * Error message
     */
    message: string;
    /**
     * Error type/reason
     */
    error: string;
};

export type VerifyPhoneDto = {
    [key: string]: unknown;
};

export type PhoneVerificationResponseDto = {
    /**
     * Success message
     */
    message: string;
    /**
     * User data with verified phone
     */
    data: UserResponseDto;
};

export type CustomerSignupResponseDto = {
    /**
     * Success message with verification instructions
     */
    message: string;
    /**
     * User data
     */
    data: UserResponseDto;
};

export type SignInDto = {
    [key: string]: unknown;
};

export type LoginResponseDto = {
    /**
     * Success message
     */
    message: string;
    /**
     * User data (password excluded)
     */
    data: UserResponseDto;
};

export type ForgotPasswordDto = {
    [key: string]: unknown;
};

export type PasswordResetEmailResponseDto = {
    /**
     * Success message with email address
     */
    message: string;
    /**
     * User data
     */
    data: UserResponseDto;
};

export type ResetPasswordDto = {
    [key: string]: unknown;
};

export type PasswordResetResponseDto = {
    /**
     * Success message
     */
    message: string;
    /**
     * User data
     */
    data: UserResponseDto;
};

export type TokenRefreshResponseDto = {
    /**
     * Success message
     */
    message: string;
};

export type LogoutResponseDto = {
    /**
     * Success message
     */
    message: string;
};

export type CreateAdminDto = {
    [key: string]: unknown;
};

export type AdminCreationResponseDto = {
    /**
     * Success message with email notification
     */
    message: string;
    /**
     * Admin user data (password excluded)
     */
    data: UserResponseDto;
};

export type ChangePasswordDto = {
    [key: string]: unknown;
};

export type PasswordChangeResponseDto = {
    /**
     * Success message
     */
    message: string;
    /**
     * User data
     */
    data: UserResponseDto;
};

export type ResendVerificationDto = {
    /**
     * Email address to resend verification to
     */
    email: string;
};

export type ResendVerificationResponseDto = {
    /**
     * Success message with email address
     */
    message: string;
    /**
     * User data
     */
    data: UserResponseDto;
};

export type UpdateUserDto = {
    [key: string]: unknown;
};

export type ChangeStatusDto = {
    [key: string]: unknown;
};

export type ChangeRoleDto = {
    [key: string]: unknown;
};

export type AddCooperativeDto = {
    /**
     * The name of the cooperative
     */
    name: string;
    /**
     * The community or location where the cooperative operates
     */
    community: string;
    /**
     * The registration fee for joining the cooperative (in local currency)
     */
    registrationFee: string;
    /**
     * The monthly membership fee for the cooperative (in local currency)
     */
    monthlyFee: string;
    /**
     * The minimum share amount required for membership (in local currency)
     */
    minimalShare: string;
};

export type EditCooperativeDto = {
    /**
     * The UUID of the cooperative to edit
     */
    id: string;
    /**
     * The updated name of the cooperative
     */
    name: string;
    /**
     * The updated community or location where the cooperative operates
     */
    community: string;
    /**
     * The updated registration fee for joining the cooperative (in local currency)
     */
    registrationFee: string;
    /**
     * The updated monthly membership fee for the cooperative (in local currency)
     */
    monthlyFee: string;
    /**
     * The updated minimum share amount required for membership (in local currency)
     */
    minimalShare: string;
};

export type AddCooperativeMemberDto = {
    /**
     * The full name of the cooperative member
     */
    name: string;
    /**
     * The UUID of the cooperative this member belongs to
     */
    cooperative: string;
    /**
     * The phone number of the member (must be unique, Ghana format)
     */
    phoneNumber: string;
    /**
     * The house number or residential address identifier
     */
    houseNumber: string;
    /**
     * The GPS address or digital address
     */
    gpsAddress: string;
    /**
     * The profile image URL or file reference (uploaded separately)
     */
    image?: string;
    /**
     * The type of identification document (e.g., National ID, Voter ID, Passport)
     */
    idType: 'Ghana Card' | 'Voter ID' | 'Passport' | 'Driver License' | 'NHIS Card';
    /**
     * The identification number (must be unique)
     */
    idNumber: string;
    /**
     * The community or locality where the member resides
     */
    community: string;
    /**
     * The district where the member resides
     */
    district: string;
    /**
     * The region of Ghana where the member resides
     */
    region: 'Ahafo Region' | 'Ashanti Region' | 'Bono East Region' | 'Bono Region' | 'Central Region' | 'Eastern Region' | 'Greater Accra Region' | 'North East Region' | 'Northern Region' | 'Oti Region' | 'Savannah Region' | 'Upper East Region' | 'Upper West Region' | 'Volta Region' | 'Western North Region' | 'Western Region';
    /**
     * The date of birth of the member (ISO 8601 format)
     */
    dob: string;
    /**
     * The highest level of education attained
     */
    education: 'No Formal Education' | 'Primary School' | 'Junior High School' | 'Senior High School' | 'Tertiary Education' | 'Vocational Training';
    /**
     * The primary occupation of the member
     */
    occupation: string;
    /**
     * The secondary occupation of the member (if any)
     */
    secondaryOccupation?: string;
    /**
     * The types of crops cultivated by the member (comma-separated)
     */
    crops: string;
    /**
     * The size of the farm in acres
     */
    farmSize: number;
};

export type EditCooperativeMemberDto = {
    /**
     * The UUID of the cooperative member to edit
     */
    id: string;
    /**
     * The updated full name of the cooperative member
     */
    name: string;
    /**
     * The UUID of the cooperative this member belongs to
     */
    cooperative: string;
    /**
     * The updated phone number of the member (must be unique, Ghana format)
     */
    phoneNumber: string;
    /**
     * The updated house number or residential address identifier
     */
    houseNumber: string;
    /**
     * The updated GPS address or digital address
     */
    gpsAddress: string;
    /**
     * The updated profile image URL or file reference (uploaded separately)
     */
    image?: string;
    /**
     * The updated type of identification document (e.g., National ID, Voter ID, Passport)
     */
    idType: 'Ghana Card' | 'Voter ID' | 'Passport' | 'Driver License' | 'NHIS Card';
    /**
     * The updated identification number (must be unique)
     */
    idNumber: string;
    /**
     * The updated community or locality where the member resides
     */
    community: string;
    /**
     * The updated district where the member resides
     */
    district: string;
    /**
     * The updated region of Ghana where the member resides
     */
    region: 'Ahafo Region' | 'Ashanti Region' | 'Bono East Region' | 'Bono Region' | 'Central Region' | 'Eastern Region' | 'Greater Accra Region' | 'North East Region' | 'Northern Region' | 'Oti Region' | 'Savannah Region' | 'Upper East Region' | 'Upper West Region' | 'Volta Region' | 'Western North Region' | 'Western Region';
    /**
     * The updated date of birth of the member (ISO 8601 format)
     */
    dob: string;
    /**
     * The updated highest level of education attained
     */
    education: 'No Formal Education' | 'Primary School' | 'Junior High School' | 'Senior High School' | 'Tertiary Education' | 'Vocational Training';
    /**
     * The updated primary occupation of the member
     */
    occupation: string;
    /**
     * The updated secondary occupation of the member (if any)
     */
    secondaryOccupation?: string;
    /**
     * The updated types of crops cultivated by the member (comma-separated)
     */
    crops: string;
    /**
     * The updated size of the farm in acres
     */
    farmSize: number;
};

export type ProductResponseDto = {
    id: string;
    sku: string;
    name: string;
    ingredients: Array<string>;
    weight: string;
    unitOfMeasurement: 'kilogram' | 'gram' | 'litre' | 'millilitre';
    category: 'Shea Butter' | 'Black Soap' | 'Cosmetics' | 'Shea Soap' | 'Powdered Soap' | 'Dawadawa' | 'Essential Oils' | 'Hair Oil' | 'Grains' | 'Legumes' | 'Other';
    description: string;
    status: 'active' | 'inactive' | 'out_of_stock' | 'discontinued';
    images: Array<string>;
    image: string;
    /**
     * Wholesale price per unit
     */
    wholesale: number;
    /**
     * Retail price per unit
     */
    retail: number;
    /**
     * Price for a full box
     */
    inBoxPrice?: number;
    quantityInBox?: number;
    favorite: boolean;
    rating: number;
    reviews: number;
    grade: 'A' | 'B' | 'premium' | 'standard' | 'organic';
    isFeatured: boolean;
    isOrganic: boolean;
    certifications: Array<string>;
    supplierReference: string;
    minOrderQuantity: number;
    createdAt: string;
    updatedAt: string;
};

export type ProductsPaginationResponseDto = {
    totalItems: number;
    currentPage: number;
    totalPages: number;
    products: Array<ProductResponseDto>;
};

export type BestProductsResponseDto = {
    totalItems: number;
    data: Array<ProductResponseDto>;
};

export type BestProductsApiResponseDto = {
    /**
     * Response message indicating whether products are personalized or curated
     */
    message: string;
    data: BestProductsResponseDto;
};

export type CreateProductDto = {
    /**
     * Unique SKU code for the product
     */
    sku?: string;
    /**
     * Product name
     */
    name: string;
    /**
     * Product ingredients (comma-separated or array)
     */
    ingredients: Array<string>;
    /**
     * Product weight description
     */
    weight?: string;
    /**
     * Unit of measurement for the product weight
     */
    unitOfMeasurement?: 'kilogram' | 'gram' | 'litre' | 'millilitre';
    /**
     * Product category
     */
    category: 'Shea Butter' | 'Black Soap' | 'Cosmetics' | 'Shea Soap' | 'Powdered Soap' | 'Dawadawa' | 'Essential Oils' | 'Hair Oil' | 'Grains' | 'Legumes' | 'Other';
    /**
     * Detailed product description
     */
    description: string;
    /**
     * Product status
     */
    status?: 'active' | 'inactive' | 'out_of_stock' | 'discontinued';
    /**
     * Product images URLs
     */
    images?: Array<string>;
    /**
     * Primary product image URL (for backward compatibility)
     */
    image?: string;
    /**
     * Wholesale price per unit
     */
    wholesale: number;
    /**
     * Retail price per unit
     */
    retail: number;
    /**
     * Price for a full box
     */
    inBoxPrice?: number;
    /**
     * Quantity of items in one box
     */
    quantityInBox?: number;
    /**
     * Product grade/quality
     */
    grade?: 'A' | 'B' | 'premium' | 'standard' | 'organic';
    /**
     * Whether product is featured
     */
    isFeatured?: boolean;
    /**
     * Whether product is organic certified
     */
    isOrganic?: boolean;
    /**
     * Product certifications
     */
    certifications?: Array<string>;
    /**
     * Supplier reference ID
     */
    supplierReference?: string;
    /**
     * Minimum order quantity
     */
    minOrderQuantity?: number;
    /**
     * Cost price for internal tracking
     */
    costPrice?: number;
};

export type UpdateProductDto = {
    /**
     * Unique SKU code for the product
     */
    sku?: string;
    /**
     * Product name
     */
    name?: string;
    /**
     * Product ingredients (comma-separated or array)
     */
    ingredients?: Array<string>;
    /**
     * Product weight description
     */
    weight?: string;
    /**
     * Unit of measurement for the product weight
     */
    unitOfMeasurement?: 'kilogram' | 'gram' | 'litre' | 'millilitre';
    /**
     * Product category
     */
    category?: 'Shea Butter' | 'Black Soap' | 'Cosmetics' | 'Shea Soap' | 'Powdered Soap' | 'Dawadawa' | 'Essential Oils' | 'Hair Oil' | 'Grains' | 'Legumes' | 'Other';
    /**
     * Detailed product description
     */
    description?: string;
    /**
     * Product status
     */
    status?: 'active' | 'inactive' | 'out_of_stock' | 'discontinued';
    /**
     * Product images URLs
     */
    images?: Array<string>;
    /**
     * Primary product image URL (for backward compatibility)
     */
    image?: string;
    /**
     * Wholesale price per unit
     */
    wholesale?: number;
    /**
     * Retail price per unit
     */
    retail?: number;
    /**
     * Price for a full box
     */
    inBoxPrice?: number;
    /**
     * Quantity of items in one box
     */
    quantityInBox?: number;
    /**
     * Product grade/quality
     */
    grade?: 'A' | 'B' | 'premium' | 'standard' | 'organic';
    /**
     * Whether product is featured
     */
    isFeatured?: boolean;
    /**
     * Whether product is organic certified
     */
    isOrganic?: boolean;
    /**
     * Product certifications
     */
    certifications?: Array<string>;
    /**
     * Supplier reference ID
     */
    supplierReference?: string;
    /**
     * Minimum order quantity
     */
    minOrderQuantity?: number;
    /**
     * Cost price for internal tracking
     */
    costPrice?: number;
    /**
     * Whether to mark this update as a minor change
     */
    isMinorUpdate?: boolean;
};

export type CreateBatchDto = {
    /**
     * Unique batch number (auto-generated if not provided)
     */
    batchNumber?: string;
    /**
     * ID of the product this batch belongs to
     */
    productId: string;
    /**
     * Quantity of items in this batch
     */
    quantity: number;
    /**
     * Production/manufacturing date
     */
    productionDate?: string;
    /**
     * Expiry date
     */
    expiryDate?: string;
    /**
     * Manufacturing location
     */
    manufacturingLocation?: string;
    /**
     * Quality check status
     */
    qualityCheckStatus?: string;
    /**
     * Additional notes about the batch
     */
    notes?: string;
};

export type BatchResponseDto = {
    /**
     * Unique identifier for the batch
     */
    id: string;
    /**
     * Unique batch number
     */
    batchNumber: string;
    /**
     * Date when the batch was produced
     */
    productionDate?: string;
    /**
     * Date when the batch expires
     */
    expiryDate?: string;
    /**
     * Location where the batch was manufactured
     */
    manufacturingLocation?: string;
    /**
     * Quality check status of the batch
     */
    qualityCheckStatus?: string;
    /**
     * Additional notes about the batch
     */
    notes?: string;
    /**
     * Quantity of items in the batch
     */
    quantity: number;
    /**
     * Whether the batch is active
     */
    isActive: boolean;
    /**
     * Associated product
     */
    product: ProductResponseDto;
    /**
     * Batch creation date
     */
    createdAt: string;
    /**
     * Last update date
     */
    updatedAt: string;
    /**
     * Deletion date (soft delete)
     */
    deletedAt?: string;
};

export type CreateIngredientDto = {
    [key: string]: unknown;
};

export type UpdateIngredientDto = {
    [key: string]: unknown;
};

export type CartProductDto = {
    /**
     * Product ID
     */
    id: string;
    /**
     * Product SKU
     */
    sku: string | null;
    /**
     * Product name
     */
    name: string;
    /**
     * Product category
     */
    category: 'Shea Butter' | 'Black Soap' | 'Cosmetics' | 'Shea Soap' | 'Powdered Soap' | 'Dawadawa' | 'Essential Oils' | 'Hair Oil' | 'Grains' | 'Legumes' | 'Other';
    /**
     * Product description
     */
    description: string | null;
    /**
     * Product status
     */
    status: 'active' | 'inactive' | 'out_of_stock' | 'discontinued';
    /**
     * Product images URLs
     */
    images: Array<string> | null;
    /**
     * Main product image URL
     */
    image: string | null;
    /**
     * Wholesale price
     */
    wholesale: number;
    /**
     * Retail price
     */
    retail: number;
    /**
     * In-box price
     */
    inBoxPrice: number | null;
    /**
     * Quantity per box
     */
    quantityInBox: number | null;
    /**
     * Is product marked as favorite
     */
    favorite: boolean;
    /**
     * Product rating
     */
    rating: number;
    /**
     * Number of reviews
     */
    reviews: number;
    /**
     * Product weight
     */
    weight: string | null;
};

export type CartItemDto = {
    /**
     * Cart item ID
     */
    id: string;
    /**
     * Product details
     */
    product: CartProductDto;
    /**
     * Quantity of product in cart
     */
    quantity: number;
    /**
     * Cart item creation date
     */
    createdAt: string;
    /**
     * Cart item last update date
     */
    updatedAt: string;
};

export type CartDataDto = {
    /**
     * Array of cart items
     */
    items: Array<CartItemDto>;
    /**
     * Total number of items in cart
     */
    count: number;
    /**
     * Total price of all items in cart
     */
    total: number;
};

export type GetCartResponseDto = {
    /**
     * Success message
     */
    message: string;
    /**
     * Cart data containing items, count, and total price
     */
    data: CartDataDto;
};

export type DeleteCartResponseDto = {
    /**
     * Success message
     */
    message: string;
    /**
     * Delete operation result
     */
    data: {
        [key: string]: unknown;
    };
};

export type AddCartDto = {
    /**
     * The UUID of the product to add to cart
     */
    id: string;
};

export type CartResponseDto = {
    /**
     * Success message
     */
    message: string;
    /**
     * Cart item data
     */
    data: CartItemDto;
};

export type AddQuantityDto = {
    /**
     * The quantity of the product in the cart (must be a positive integer)
     */
    quantity: number;
};

export type AddBulkCartItemDto = {
    /**
     * The UUID of the product to add to cart
     */
    productId: string;
    /**
     * The quantity of the product in the cart (must be a positive integer)
     */
    quantity: number;
};

export type BulkAddCartDto = {
    /**
     * Array of cart items to add with their quantities
     */
    items: Array<AddBulkCartItemDto>;
};

export type BulkAddCartDataDto = {
    /**
     * Array of successfully added cart items
     */
    addedItems: Array<CartItemDto>;
    /**
     * Array of product IDs that were skipped (not found or invalid)
     */
    skippedItems: Array<string>;
};

export type BulkAddCartResponseDto = {
    /**
     * Success message with details about added and skipped items
     */
    message: string;
    /**
     * Details of added items and skipped items
     */
    data: BulkAddCartDataDto;
};

export type InitializeTransaction = {
    [key: string]: unknown;
};

export type OrderStatus = {
    [key: string]: unknown;
};

export type PaymentStatus = {
    [key: string]: unknown;
};

export type UploadResponseDto = {
    /**
     * Success message
     */
    message: string;
    /**
     * The URL of the uploaded image
     */
    data: string;
};

export type BatchAllocationDto = {
    batchId: string;
    quantity: number;
};

export type SaleLineItemDto = {
    productId: string;
    batchAllocations: Array<BatchAllocationDto>;
    requestedQuantity: number;
    customPrice?: number;
};

export type CreateSaleDto = {
    customerId: string;
    status?: 'invoice_requested' | 'pending_payment' | 'paid' | 'packaging' | 'in_transit' | 'delivered';
    lineItems: Array<SaleLineItemDto>;
};

export type Sale = {
    [key: string]: unknown;
};

export type UpdateSaleLineItemDto = {
    productId?: string;
    batchAllocations?: Array<BatchAllocationDto>;
    requestedQuantity?: number;
    customPrice?: number;
};

export type UpdateSaleDto = {
    customerId?: string;
    status?: 'invoice_requested' | 'pending_payment' | 'paid' | 'packaging' | 'in_transit' | 'delivered';
    lineItems?: Array<UpdateSaleLineItemDto>;
};

export type UpdateSaleStatusDto = {
    status: 'invoice_requested' | 'pending_payment' | 'paid' | 'packaging' | 'in_transit' | 'delivered';
};

export type AddLineItemDto = {
    productId: string;
    batchAllocations: Array<BatchAllocationDto>;
    requestedQuantity: number;
    customPrice?: number;
};

export type AssignBatchesDto = {
    productId: string;
    batchAllocations: Array<BatchAllocationDto>;
};

export type GenerateInvoiceDto = {
    /**
     * Discount amount
     */
    discount?: number;
    /**
     * Transportation cost
     */
    transportation?: number;
};

export type GenerateReceiptDto = {
    /**
     * Payment method
     */
    paymentMethod?: string;
    /**
     * Discount amount
     */
    discount?: number;
    /**
     * Transportation cost
     */
    transportation?: number;
};

export type DriverDetailsDto = {
    /**
     * Driver name
     */
    name: string;
    /**
     * Vehicle/Truck number
     */
    vehicleNumber: string;
    /**
     * Driver phone number
     */
    phoneNumber: string;
    /**
     * Driver email
     */
    email?: string;
};

export type ReceiverDetailsDto = {
    /**
     * Receiver name
     */
    name: string;
    /**
     * Receiver phone number
     */
    phone: string;
    /**
     * Receiver email
     */
    email?: string;
    /**
     * Receiver address
     */
    address?: string;
};

export type GenerateWaybillDto = {
    /**
     * Driver details
     */
    driver: DriverDetailsDto;
    /**
     * Receiver details (falls back to customer if not provided)
     */
    receiver?: ReceiverDetailsDto;
    /**
     * Remarks about the condition of goods
     */
    remarks?: string;
};

export type CreateCustomerDto = {
    /**
     * The name of the customer
     */
    name: string;
    /**
     * The phone number of the customer
     */
    phone?: string;
    /**
     * The email address of the customer
     */
    email?: string;
    /**
     * The address of the customer
     */
    address?: string;
};

export type UpdateCustomerDto = {
    /**
     * The ID of the customer to update
     */
    id: string;
    /**
     * The name of the customer
     */
    name?: string;
    /**
     * The phone number of the customer
     */
    phone?: string;
    /**
     * The email address of the customer
     */
    email?: string;
    /**
     * The address of the customer
     */
    address?: string;
};

export type ProfileResponseDto = {
    /**
     * User ID
     */
    id: string;
    /**
     * Full name
     */
    name: string;
    /**
     * Email address
     */
    email: string;
    /**
     * Phone number
     */
    phone?: string;
    /**
     * Profile avatar URL
     */
    avatarUrl?: string;
    /**
     * User role (read-only)
     */
    userType: 'user' | 'admin' | 'superadmin';
    /**
     * Email verification status (read-only)
     */
    emailVerified: boolean;
    /**
     * Phone verification status (read-only)
     */
    phoneVerified: boolean;
    /**
     * Account creation date (read-only)
     */
    createdAt: string;
    /**
     * Last update date (read-only)
     */
    updatedAt: string;
};

export type UpdateProfileDto = {
    /**
     * Full name
     */
    name?: string;
    /**
     * Phone number
     */
    phone?: string;
};

export type ContactUsDto = {
    /**
     * Full name of the person contacting
     */
    fullName?: string;
    /**
     * Email address of the person contacting
     */
    email?: string;
    /**
     * Phone number of the person contacting (accepts international formats)
     */
    phoneNumber?: string;
    /**
     * Message content (minimum 10 characters)
     */
    message: string;
};

export type ContactUsSuccessResponseDto = {
    /**
     * Indicates if the operation was successful
     */
    success: boolean;
    /**
     * Success message
     */
    message: string;
};

export type ContactUsErrorResponseDto = {
    /**
     * Indicates if the operation was successful
     */
    success: boolean;
    /**
     * Error message
     */
    error: string;
};

export type AuditControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date for filtering (ISO 8601 format)
         */
        from?: unknown;
        /**
         * End date for filtering (ISO 8601 format)
         */
        to?: unknown;
        /**
         * Filter by action type
         */
        actionType?: 'LOGIN' | 'LOGOUT' | 'LOGIN_FAILED' | 'PASSWORD_CHANGED' | 'PASSWORD_RESET' | 'CREATE' | 'UPDATE' | 'DELETE' | 'ROLE_CHANGED' | 'PERMISSION_CHANGED' | 'STATUS_CHANGED' | 'INVENTORY_ADJUSTED' | 'BATCH_ASSIGNED' | 'REPORT_EXPORTED' | 'DATA_EXPORTED' | 'SALE_CREATED' | 'SALE_UPDATED' | 'SALE_CANCELLED' | 'CONFIGURATION_CHANGED' | 'SYSTEM_ACTION' | 'USER_CREATED' | 'USER_UPDATED' | 'USER_DELETED' | 'USER_DEACTIVATED' | 'USER_ACTIVATED';
        /**
         * Filter by entity type
         */
        entityType?: 'USER' | 'PRODUCT' | 'BATCH' | 'INVENTORY' | 'SALE' | 'CHECKOUT' | 'CART' | 'COOPERATIVE' | 'COOPERATIVE_MEMBER' | 'CUSTOMER' | 'REPORT' | 'SYSTEM' | 'CONFIGURATION' | 'AUTHENTICATION';
        /**
         * Filter by user ID who performed the action
         */
        userId?: unknown;
        /**
         * Filter by user role
         */
        role?: 'user' | 'admin' | 'superadmin';
        /**
         * Page number (starts from 1)
         */
        page?: unknown;
        /**
         * Number of items per page
         */
        limit?: unknown;
        /**
         * Sort order (ASC or DESC)
         */
        sortOrder?: unknown;
    };
    url: '/audits';
};

export type AuditControllerFindAllResponses = {
    /**
     * Audit logs retrieved successfully
     */
    200: Array<AuditLogResponseDto>;
};

export type AuditControllerFindAllResponse = AuditControllerFindAllResponses[keyof AuditControllerFindAllResponses];

export type AuditControllerFindOneData = {
    body?: never;
    path: {
        /**
         * Audit Log ID
         */
        id: string;
    };
    query?: never;
    url: '/audits/{id}';
};

export type AuditControllerFindOneResponses = {
    /**
     * Audit log retrieved successfully
     */
    200: AuditLogResponseDto;
};

export type AuditControllerFindOneResponse = AuditControllerFindOneResponses[keyof AuditControllerFindOneResponses];

export type AuditControllerGetStatisticsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date (ISO 8601 format)
         */
        from?: string;
        /**
         * End date (ISO 8601 format)
         */
        to?: string;
    };
    url: '/audits/stats/overview';
};

export type AuditControllerGetStatisticsResponses = {
    /**
     * Audit statistics retrieved successfully
     */
    200: unknown;
};

export type AuthenticationControllerRegisterData = {
    body: RegisterUserDto;
    path?: never;
    query?: never;
    url: '/authentication/sign-up';
};

export type AuthenticationControllerRegisterErrors = {
    /**
     * Bad request - validation failed
     */
    400: ValidationErrorResponseDto;
    /**
     * User with email already exists
     */
    409: ErrorResponseDto;
};

export type AuthenticationControllerRegisterError = AuthenticationControllerRegisterErrors[keyof AuthenticationControllerRegisterErrors];

export type AuthenticationControllerRegisterResponses = {
    /**
     * User registration successful
     */
    201: AuthResponseDto;
};

export type AuthenticationControllerRegisterResponse = AuthenticationControllerRegisterResponses[keyof AuthenticationControllerRegisterResponses];

export type AuthenticationControllerVerifyPhoneData = {
    body: VerifyPhoneDto;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/authentication/verify-phone/{id}';
};

export type AuthenticationControllerVerifyPhoneErrors = {
    /**
     * Bad request - invalid OTP code or validation failed
     */
    400: ValidationErrorResponseDto;
    /**
     * Unauthorized - invalid or missing token
     */
    401: ErrorResponseDto;
    /**
     * User not found
     */
    404: ErrorResponseDto;
    /**
     * User with phone number already exists
     */
    409: ErrorResponseDto;
};

export type AuthenticationControllerVerifyPhoneError = AuthenticationControllerVerifyPhoneErrors[keyof AuthenticationControllerVerifyPhoneErrors];

export type AuthenticationControllerVerifyPhoneResponses = {
    /**
     * Phone verification successful
     */
    200: PhoneVerificationResponseDto;
};

export type AuthenticationControllerVerifyPhoneResponse = AuthenticationControllerVerifyPhoneResponses[keyof AuthenticationControllerVerifyPhoneResponses];

export type AuthenticationControllerCustomerSignupData = {
    body: RegisterUserDto;
    path?: never;
    query?: never;
    url: '/authentication/customer-signup';
};

export type AuthenticationControllerCustomerSignupErrors = {
    /**
     * Bad request - validation failed
     */
    400: ValidationErrorResponseDto;
    /**
     * User with email already exists
     */
    409: ErrorResponseDto;
};

export type AuthenticationControllerCustomerSignupError = AuthenticationControllerCustomerSignupErrors[keyof AuthenticationControllerCustomerSignupErrors];

export type AuthenticationControllerCustomerSignupResponses = {
    /**
     * Customer account created, verification email sent
     */
    201: CustomerSignupResponseDto;
};

export type AuthenticationControllerCustomerSignupResponse = AuthenticationControllerCustomerSignupResponses[keyof AuthenticationControllerCustomerSignupResponses];

export type AuthenticationControllerSignInData = {
    body: SignInDto;
    path?: never;
    query?: never;
    url: '/authentication/login';
};

export type AuthenticationControllerSignInErrors = {
    /**
     * Bad request - validation failed
     */
    400: ValidationErrorResponseDto;
    /**
     * Invalid email or password
     */
    401: ErrorResponseDto;
    /**
     * Account is inactive or suspended
     */
    403: ErrorResponseDto;
};

export type AuthenticationControllerSignInError = AuthenticationControllerSignInErrors[keyof AuthenticationControllerSignInErrors];

export type AuthenticationControllerSignInResponses = {
    /**
     * Login successful, tokens set in cookies (accessToken: 15min, refreshToken: 1day)
     */
    200: LoginResponseDto;
};

export type AuthenticationControllerSignInResponse = AuthenticationControllerSignInResponses[keyof AuthenticationControllerSignInResponses];

export type AuthenticationControllerForgotPasswordData = {
    body: ForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/authentication/forgot-password';
};

export type AuthenticationControllerForgotPasswordErrors = {
    /**
     * Bad request - validation failed
     */
    400: ValidationErrorResponseDto;
    /**
     * User with email does not exist
     */
    404: ErrorResponseDto;
};

export type AuthenticationControllerForgotPasswordError = AuthenticationControllerForgotPasswordErrors[keyof AuthenticationControllerForgotPasswordErrors];

export type AuthenticationControllerForgotPasswordResponses = {
    /**
     * Password reset email sent successfully
     */
    200: PasswordResetEmailResponseDto;
};

export type AuthenticationControllerForgotPasswordResponse = AuthenticationControllerForgotPasswordResponses[keyof AuthenticationControllerForgotPasswordResponses];

export type AuthenticationControllerResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/authentication/reset-password';
};

export type AuthenticationControllerResetPasswordErrors = {
    /**
     * Bad request - passwords do not match or validation failed
     */
    400: ValidationErrorResponseDto;
    /**
     * User not found or invalid token
     */
    404: ErrorResponseDto;
    /**
     * Reset token has expired
     */
    410: ErrorResponseDto;
};

export type AuthenticationControllerResetPasswordError = AuthenticationControllerResetPasswordErrors[keyof AuthenticationControllerResetPasswordErrors];

export type AuthenticationControllerResetPasswordResponses = {
    /**
     * Password reset successful
     */
    200: PasswordResetResponseDto;
};

export type AuthenticationControllerResetPasswordResponse = AuthenticationControllerResetPasswordResponses[keyof AuthenticationControllerResetPasswordResponses];

export type AuthenticationControllerEmailVerificationData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
        /**
         * Verification token
         */
        token: string;
    };
    query?: never;
    url: '/authentication/verify/{id}/{token}';
};

export type AuthenticationControllerEmailVerificationErrors = {
    /**
     * Token does not exist or has expired
     */
    401: ErrorResponseDto;
    /**
     * User not found
     */
    404: ErrorResponseDto;
};

export type AuthenticationControllerEmailVerificationError = AuthenticationControllerEmailVerificationErrors[keyof AuthenticationControllerEmailVerificationErrors];

export type AuthenticationControllerEmailVerificationResponses = {
    /**
     * Email verification successful and user logged in
     */
    200: LoginResponseDto;
};

export type AuthenticationControllerEmailVerificationResponse = AuthenticationControllerEmailVerificationResponses[keyof AuthenticationControllerEmailVerificationResponses];

export type AuthenticationControllerRefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/authentication/refresh-token';
};

export type AuthenticationControllerRefreshTokenErrors = {
    /**
     * Invalid, expired, or missing refresh token
     */
    401: ErrorResponseDto;
    /**
     * User not found
     */
    404: ErrorResponseDto;
};

export type AuthenticationControllerRefreshTokenError = AuthenticationControllerRefreshTokenErrors[keyof AuthenticationControllerRefreshTokenErrors];

export type AuthenticationControllerRefreshTokenResponses = {
    /**
     * Tokens refreshed successfully, new tokens set in cookies (accessToken: 15min, refreshToken: 1day)
     */
    200: TokenRefreshResponseDto;
};

export type AuthenticationControllerRefreshTokenResponse = AuthenticationControllerRefreshTokenResponses[keyof AuthenticationControllerRefreshTokenResponses];

export type AuthenticationControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/authentication/logout';
};

export type AuthenticationControllerLogoutErrors = {
    /**
     * Unauthorized - not logged in
     */
    401: ErrorResponseDto;
};

export type AuthenticationControllerLogoutError = AuthenticationControllerLogoutErrors[keyof AuthenticationControllerLogoutErrors];

export type AuthenticationControllerLogoutResponses = {
    /**
     * Logged out successfully, cookies cleared
     */
    200: LogoutResponseDto;
};

export type AuthenticationControllerLogoutResponse = AuthenticationControllerLogoutResponses[keyof AuthenticationControllerLogoutResponses];

export type AuthenticationControllerCreateAdminData = {
    body: CreateAdminDto;
    path?: never;
    query?: never;
    url: '/authentication/create-admin';
};

export type AuthenticationControllerCreateAdminErrors = {
    /**
     * Bad request - email must be @maltitiaenterprise.com or validation failed
     */
    400: ValidationErrorResponseDto;
    /**
     * Unauthorized - not logged in
     */
    401: ErrorResponseDto;
    /**
     * Forbidden - requires Super Admin role
     */
    403: ErrorResponseDto;
    /**
     * User with email already exists
     */
    409: ErrorResponseDto;
};

export type AuthenticationControllerCreateAdminError = AuthenticationControllerCreateAdminErrors[keyof AuthenticationControllerCreateAdminErrors];

export type AuthenticationControllerCreateAdminResponses = {
    /**
     * Admin account created successfully, credentials sent to email
     */
    201: AdminCreationResponseDto;
};

export type AuthenticationControllerCreateAdminResponse = AuthenticationControllerCreateAdminResponses[keyof AuthenticationControllerCreateAdminResponses];

export type AuthenticationControllerChangePasswordData = {
    body: ChangePasswordDto;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/authentication/change-password/{id}';
};

export type AuthenticationControllerChangePasswordErrors = {
    /**
     * Bad request - passwords do not match, current password is incorrect, or validation failed
     */
    400: ValidationErrorResponseDto;
    /**
     * Unauthorized - not logged in
     */
    401: ErrorResponseDto;
    /**
     * User not found
     */
    404: ErrorResponseDto;
};

export type AuthenticationControllerChangePasswordError = AuthenticationControllerChangePasswordErrors[keyof AuthenticationControllerChangePasswordErrors];

export type AuthenticationControllerChangePasswordResponses = {
    /**
     * Password changed successfully
     */
    200: PasswordChangeResponseDto;
};

export type AuthenticationControllerChangePasswordResponse = AuthenticationControllerChangePasswordResponses[keyof AuthenticationControllerChangePasswordResponses];

export type AuthenticationControllerResendVerificationEmailData = {
    body: ResendVerificationDto;
    path?: never;
    query?: never;
    url: '/authentication/resend-verification';
};

export type AuthenticationControllerResendVerificationEmailErrors = {
    /**
     * Bad request - email already verified or validation failed
     */
    400: ValidationErrorResponseDto;
    /**
     * User with email does not exist
     */
    404: ErrorResponseDto;
};

export type AuthenticationControllerResendVerificationEmailError = AuthenticationControllerResendVerificationEmailErrors[keyof AuthenticationControllerResendVerificationEmailErrors];

export type AuthenticationControllerResendVerificationEmailResponses = {
    /**
     * Verification email resent successfully
     */
    200: ResendVerificationResponseDto;
};

export type AuthenticationControllerResendVerificationEmailResponse = AuthenticationControllerResendVerificationEmailResponses[keyof AuthenticationControllerResendVerificationEmailResponses];

export type UsersControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type UsersControllerFindAllResponses = {
    /**
     * Users retrieved successfully
     */
    200: Array<UserResponseDto>;
};

export type UsersControllerFindAllResponse = UsersControllerFindAllResponses[keyof UsersControllerFindAllResponses];

export type UsersControllerRemoveData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersControllerRemoveResponses = {
    /**
     * User deleted successfully
     */
    200: unknown;
};

export type UsersControllerFindOneData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersControllerFindOneResponses = {
    /**
     * User retrieved successfully
     */
    200: UserResponseDto;
};

export type UsersControllerFindOneResponse = UsersControllerFindOneResponses[keyof UsersControllerFindOneResponses];

export type UsersControllerUpdateData = {
    body: UpdateUserDto;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersControllerUpdateResponses = {
    /**
     * User updated successfully
     */
    200: UserResponseDto;
};

export type UsersControllerUpdateResponse = UsersControllerUpdateResponses[keyof UsersControllerUpdateResponses];

export type UsersControllerChangeStatusData = {
    body: ChangeStatusDto;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}/status';
};

export type UsersControllerChangeStatusResponses = {
    /**
     * User status changed successfully
     */
    200: UserResponseDto;
};

export type UsersControllerChangeStatusResponse = UsersControllerChangeStatusResponses[keyof UsersControllerChangeStatusResponses];

export type UsersControllerChangeRoleData = {
    body: ChangeRoleDto;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}/role';
};

export type UsersControllerChangeRoleResponses = {
    /**
     * User role changed successfully
     */
    200: UserResponseDto;
};

export type UsersControllerChangeRoleResponse = UsersControllerChangeRoleResponses[keyof UsersControllerChangeRoleResponses];

export type CooperativeControllerGetAllCooperativesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cooperative/cooperatives';
};

export type CooperativeControllerGetAllCooperativesResponses = {
    200: unknown;
};

export type CooperativeControllerGetCooperativeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/cooperative/cooperative/{id}';
};

export type CooperativeControllerGetCooperativeResponses = {
    200: unknown;
};

export type CooperativeControllerAddCooperativeData = {
    body: AddCooperativeDto;
    path?: never;
    query?: never;
    url: '/cooperative/add-cooperative';
};

export type CooperativeControllerAddCooperativeResponses = {
    201: unknown;
};

export type CooperativeControllerEditCooperativeData = {
    body: EditCooperativeDto;
    path?: never;
    query?: never;
    url: '/cooperative/edit-cooperative';
};

export type CooperativeControllerEditCooperativeResponses = {
    200: unknown;
};

export type CooperativeControllerDeleteCooperativeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/cooperative/delete-cooperative/{id}';
};

export type CooperativeControllerDeleteCooperativeResponses = {
    200: unknown;
};

export type CooperativeControllerGetAllCooperativeMembersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cooperative/members';
};

export type CooperativeControllerGetAllCooperativeMembersResponses = {
    200: unknown;
};

export type CooperativeControllerGetCooperativeMemberData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/cooperative/member/{id}';
};

export type CooperativeControllerGetCooperativeMemberResponses = {
    200: unknown;
};

export type CooperativeControllerGetMembersByCooperativeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/cooperative/cooperative-members/{id}';
};

export type CooperativeControllerGetMembersByCooperativeResponses = {
    200: unknown;
};

export type CooperativeControllerAddMemberData = {
    body: AddCooperativeMemberDto;
    path?: never;
    query?: never;
    url: '/cooperative/add-member';
};

export type CooperativeControllerAddMemberResponses = {
    201: unknown;
};

export type CooperativeControllerEditMemberData = {
    body: EditCooperativeMemberDto;
    path?: never;
    query?: never;
    url: '/cooperative/edit-member';
};

export type CooperativeControllerEditMemberResponses = {
    200: unknown;
};

export type CooperativeControllerDeleteMemberData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/cooperative/delete-member/{id}';
};

export type CooperativeControllerDeleteMemberResponses = {
    200: unknown;
};

export type ProductsControllerGetAllProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Search term for product name or description
         */
        searchTerm?: string;
        /**
         * Filter by product category
         */
        category?: 'Shea Butter' | 'Black Soap' | 'Cosmetics' | 'Shea Soap' | 'Powdered Soap' | 'Dawadawa' | 'Essential Oils' | 'Hair Oil' | 'Grains' | 'Legumes' | 'Other';
        /**
         * Filter by product status
         */
        status?: 'active' | 'inactive' | 'out_of_stock' | 'discontinued';
        /**
         * Filter by product grade
         */
        grade?: 'A' | 'B' | 'premium' | 'standard' | 'organic';
        /**
         * Filter by unit of measurement
         */
        unitOfMeasurement?: 'kilogram' | 'gram' | 'litre' | 'millilitre';
        /**
         * Filter by featured products
         */
        isFeatured?: boolean;
        /**
         * Filter by organic products
         */
        isOrganic?: boolean;
        /**
         * Minimum price filter
         */
        minPrice?: number;
        /**
         * Maximum price filter
         */
        maxPrice?: number;
        /**
         * Sort field
         */
        sortBy?: 'name' | 'retail' | 'createdAt' | 'rating' | 'stockQuantity';
        /**
         * Sort order
         */
        sortOrder?: 'ASC' | 'DESC';
        /**
         * Filter by batch ID
         */
        batchId?: string;
    };
    url: '/products/all-products';
};

export type ProductsControllerGetAllProductsErrors = {
    /**
     * Invalid query parameters
     */
    400: unknown;
};

export type ProductsControllerGetAllProductsResponses = {
    /**
     * Products retrieved successfully
     */
    200: ProductsPaginationResponseDto;
};

export type ProductsControllerGetAllProductsResponse = ProductsControllerGetAllProductsResponses[keyof ProductsControllerGetAllProductsResponses];

export type ProductsControllerGetBestProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/products/best-products';
};

export type ProductsControllerGetBestProductsResponses = {
    /**
     * Preview products retrieved successfully. Response includes personalized products for logged-in users or curated best performers for anonymous users.
     */
    200: BestProductsApiResponseDto;
};

export type ProductsControllerGetBestProductsResponse = ProductsControllerGetBestProductsResponses[keyof ProductsControllerGetBestProductsResponses];

export type ProductsControllerGetAllProductsBasicData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/products/list';
};

export type ProductsControllerGetAllProductsBasicResponses = {
    /**
     * Products retrieved successfully
     */
    200: unknown;
};

export type ProductsControllerGetProductData = {
    body?: never;
    path: {
        /**
         * Product UUID
         */
        id: string;
    };
    query?: never;
    url: '/products/product/{id}';
};

export type ProductsControllerGetProductErrors = {
    /**
     * Product not found
     */
    404: unknown;
};

export type ProductsControllerGetProductResponses = {
    /**
     * Product retrieved successfully
     */
    200: ProductResponseDto;
};

export type ProductsControllerGetProductResponse = ProductsControllerGetProductResponses[keyof ProductsControllerGetProductResponses];

export type ProductsControllerAddProductData = {
    body: CreateProductDto;
    path?: never;
    query?: never;
    url: '/products/add-product';
};

export type ProductsControllerAddProductErrors = {
    /**
     * Invalid input data
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Product with SKU already exists
     */
    409: unknown;
};

export type ProductsControllerAddProductResponses = {
    /**
     * Product created successfully
     */
    201: ProductResponseDto;
};

export type ProductsControllerAddProductResponse = ProductsControllerAddProductResponses[keyof ProductsControllerAddProductResponses];

export type ProductsControllerEditProductData = {
    body: UpdateProductDto;
    path: {
        /**
         * Product UUID
         */
        id: string;
    };
    query?: never;
    url: '/products/edit-product/{id}';
};

export type ProductsControllerEditProductErrors = {
    /**
     * Invalid input data
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Product not found
     */
    404: unknown;
    /**
     * Product with SKU already exists
     */
    409: unknown;
};

export type ProductsControllerEditProductResponses = {
    /**
     * Product updated successfully
     */
    200: ProductResponseDto;
};

export type ProductsControllerEditProductResponse = ProductsControllerEditProductResponses[keyof ProductsControllerEditProductResponses];

export type ProductsControllerDeleteProductData = {
    body?: never;
    path: {
        /**
         * Product UUID
         */
        id: string;
    };
    query?: never;
    url: '/products/delete-product/{id}';
};

export type ProductsControllerDeleteProductErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Product not found
     */
    404: unknown;
};

export type ProductsControllerDeleteProductResponses = {
    /**
     * Product deleted successfully
     */
    200: unknown;
};

export type ProductsControllerChangeProductStatusData = {
    body?: never;
    path: {
        /**
         * Product UUID
         */
        id: string;
    };
    query?: never;
    url: '/products/change-status/{id}';
};

export type ProductsControllerChangeProductStatusErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Product not found
     */
    404: unknown;
};

export type ProductsControllerChangeProductStatusResponses = {
    /**
     * Product status changed successfully
     */
    200: ProductResponseDto;
};

export type ProductsControllerChangeProductStatusResponse = ProductsControllerChangeProductStatusResponses[keyof ProductsControllerChangeProductStatusResponses];

export type ProductsControllerToggleFavoriteData = {
    body?: never;
    path: {
        /**
         * Product UUID
         */
        id: string;
    };
    query?: never;
    url: '/products/favorite/{id}';
};

export type ProductsControllerToggleFavoriteErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Product not found
     */
    404: unknown;
};

export type ProductsControllerToggleFavoriteResponses = {
    /**
     * Product favorite status toggled successfully
     */
    200: ProductResponseDto;
};

export type ProductsControllerToggleFavoriteResponse = ProductsControllerToggleFavoriteResponses[keyof ProductsControllerToggleFavoriteResponses];

export type ProductsControllerExportProductsToExcelData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search term for product name or description
         */
        searchTerm?: string;
        /**
         * Filter by product category
         */
        category?: 'Shea Butter' | 'Black Soap' | 'Cosmetics' | 'Shea Soap' | 'Powdered Soap' | 'Dawadawa' | 'Essential Oils' | 'Hair Oil' | 'Grains' | 'Legumes' | 'Other';
        /**
         * Filter by product status
         */
        status?: 'active' | 'inactive' | 'out_of_stock' | 'discontinued';
        /**
         * Filter by product grade
         */
        grade?: 'A' | 'B' | 'premium' | 'standard' | 'organic';
        /**
         * Filter by unit of measurement
         */
        unitOfMeasurement?: 'kilogram' | 'gram' | 'litre' | 'millilitre';
        /**
         * Filter by featured products
         */
        isFeatured?: boolean;
        /**
         * Filter by organic products
         */
        isOrganic?: boolean;
        /**
         * Minimum price filter
         */
        minPrice?: number;
        /**
         * Maximum price filter
         */
        maxPrice?: number;
        /**
         * Sort field
         */
        sortBy?: 'name' | 'retail' | 'createdAt' | 'rating' | 'stockQuantity';
        /**
         * Sort order
         */
        sortOrder?: 'ASC' | 'DESC';
        /**
         * Filter by batch ID
         */
        batchId?: string;
    };
    url: '/products/export/excel';
};

export type ProductsControllerExportProductsToExcelErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * No products found matching filters
     */
    404: unknown;
};

export type ProductsControllerExportProductsToExcelResponses = {
    /**
     * Excel file downloaded successfully
     */
    200: Blob | File;
};

export type ProductsControllerExportProductsToExcelResponse = ProductsControllerExportProductsToExcelResponses[keyof ProductsControllerExportProductsToExcelResponses];

export type BatchesControllerGetAllBatchesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination
         */
        page?: unknown;
        /**
         * Number of items per page
         */
        limit?: unknown;
        /**
         * Filter by product ID
         */
        productId?: unknown;
        /**
         * Search term for batch number
         */
        batchNumber?: unknown;
        /**
         * Filter by quality check status
         */
        qualityCheckStatus?: unknown;
        /**
         * Filter by active status
         */
        isActive?: unknown;
        /**
         * Sort field
         */
        sortBy?: unknown;
        /**
         * Sort order
         */
        sortOrder?: unknown;
    };
    url: '/products/batches';
};

export type BatchesControllerGetAllBatchesResponses = {
    /**
     * Batches retrieved successfully
     */
    200: {
        message?: string;
        data?: {
            batches?: Array<BatchResponseDto>;
            total?: number;
            page?: number;
            limit?: number;
        };
    };
};

export type BatchesControllerGetAllBatchesResponse = BatchesControllerGetAllBatchesResponses[keyof BatchesControllerGetAllBatchesResponses];

export type BatchesControllerCreateBatchData = {
    body: CreateBatchDto;
    path?: never;
    query?: never;
    url: '/products/batches';
};

export type BatchesControllerCreateBatchErrors = {
    /**
     * Invalid input data
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Batch number already exists
     */
    409: unknown;
};

export type BatchesControllerCreateBatchResponses = {
    /**
     * Batch created successfully
     */
    201: BatchResponseDto;
};

export type BatchesControllerCreateBatchResponse = BatchesControllerCreateBatchResponses[keyof BatchesControllerCreateBatchResponses];

export type BatchesControllerGetBatchData = {
    body?: never;
    path: {
        /**
         * Batch UUID
         */
        id: string;
    };
    query?: never;
    url: '/products/batches/{id}';
};

export type BatchesControllerGetBatchErrors = {
    /**
     * Batch not found
     */
    404: unknown;
};

export type BatchesControllerGetBatchResponses = {
    /**
     * Batch retrieved successfully
     */
    200: BatchResponseDto;
};

export type BatchesControllerGetBatchResponse = BatchesControllerGetBatchResponses[keyof BatchesControllerGetBatchResponses];

export type BatchesControllerGetBatchesByProductData = {
    body?: never;
    path: {
        /**
         * Product UUID
         */
        productId: string;
    };
    query?: never;
    url: '/products/batches/product/{productId}';
};

export type BatchesControllerGetBatchesByProductErrors = {
    /**
     * Product not found
     */
    404: unknown;
};

export type BatchesControllerGetBatchesByProductResponses = {
    /**
     * Batches retrieved successfully
     */
    200: Array<BatchResponseDto>;
};

export type BatchesControllerGetBatchesByProductResponse = BatchesControllerGetBatchesByProductResponses[keyof BatchesControllerGetBatchesByProductResponses];

export type IngredientsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ingredients';
};

export type IngredientsControllerFindAllResponses = {
    /**
     * List of all ingredients
     */
    200: unknown;
};

export type IngredientsControllerCreateData = {
    body: CreateIngredientDto;
    path?: never;
    query?: never;
    url: '/ingredients';
};

export type IngredientsControllerCreateErrors = {
    /**
     * Bad request
     */
    400: unknown;
};

export type IngredientsControllerCreateResponses = {
    /**
     * The created ingredient
     */
    201: unknown;
};

export type IngredientsControllerRemoveData = {
    body?: never;
    path: {
        /**
         * The ID of the ingredient to delete
         */
        id: string;
    };
    query?: never;
    url: '/ingredients/{id}';
};

export type IngredientsControllerRemoveErrors = {
    /**
     * Ingredient not found
     */
    404: unknown;
};

export type IngredientsControllerRemoveResponses = {
    /**
     * Ingredient deleted successfully
     */
    200: unknown;
};

export type IngredientsControllerFindOneData = {
    body?: never;
    path: {
        /**
         * The ID of the ingredient
         */
        id: string;
    };
    query?: never;
    url: '/ingredients/{id}';
};

export type IngredientsControllerFindOneErrors = {
    /**
     * Ingredient not found
     */
    404: unknown;
};

export type IngredientsControllerFindOneResponses = {
    /**
     * The ingredient object
     */
    200: unknown;
};

export type IngredientsControllerUpdateData = {
    body: UpdateIngredientDto;
    path: {
        /**
         * The ID of the ingredient to update
         */
        id: string;
    };
    query?: never;
    url: '/ingredients/{id}';
};

export type IngredientsControllerUpdateErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Ingredient not found
     */
    404: unknown;
};

export type IngredientsControllerUpdateResponses = {
    /**
     * The updated ingredient
     */
    200: unknown;
};

export type CartControllerGetCartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cart';
};

export type CartControllerGetCartErrors = {
    /**
     * Unauthorized - user not authenticated
     */
    401: ErrorResponseDto;
    /**
     * User not found
     */
    404: ErrorResponseDto;
};

export type CartControllerGetCartError = CartControllerGetCartErrors[keyof CartControllerGetCartErrors];

export type CartControllerGetCartResponses = {
    /**
     * Cart retrieved successfully. Returns array of cart items, total item count, and total price.
     */
    200: GetCartResponseDto;
};

export type CartControllerGetCartResponse = CartControllerGetCartResponses[keyof CartControllerGetCartResponses];

export type CartControllerAddToCartData = {
    /**
     * Product ID to add to cart
     */
    body: AddCartDto;
    path?: never;
    query?: never;
    url: '/cart';
};

export type CartControllerAddToCartErrors = {
    /**
     * Bad request - validation failed
     */
    400: ValidationErrorResponseDto;
    /**
     * Unauthorized - user not authenticated
     */
    401: ErrorResponseDto;
    /**
     * Product not found
     */
    404: ErrorResponseDto;
};

export type CartControllerAddToCartError = CartControllerAddToCartErrors[keyof CartControllerAddToCartErrors];

export type CartControllerAddToCartResponses = {
    /**
     * Product added to cart successfully
     */
    201: CartResponseDto;
};

export type CartControllerAddToCartResponse = CartControllerAddToCartResponses[keyof CartControllerAddToCartResponses];

export type CartControllerRemoveFromCartData = {
    body?: never;
    path: {
        /**
         * Cart item ID (UUID)
         */
        id: string;
    };
    query?: never;
    url: '/cart/{id}';
};

export type CartControllerRemoveFromCartErrors = {
    /**
     * Unauthorized - user not authenticated
     */
    401: ErrorResponseDto;
    /**
     * Forbidden - user attempting to delete another user's cart item
     */
    403: ErrorResponseDto;
    /**
     * Cart item not found
     */
    404: ErrorResponseDto;
};

export type CartControllerRemoveFromCartError = CartControllerRemoveFromCartErrors[keyof CartControllerRemoveFromCartErrors];

export type CartControllerRemoveFromCartResponses = {
    /**
     * Cart item removed successfully
     */
    200: DeleteCartResponseDto;
};

export type CartControllerRemoveFromCartResponse = CartControllerRemoveFromCartResponses[keyof CartControllerRemoveFromCartResponses];

export type CartControllerAddQuantityData = {
    /**
     * New quantity for the cart item (must be positive integer)
     */
    body: AddQuantityDto;
    path: {
        /**
         * Cart item ID (UUID)
         */
        id: string;
    };
    query?: never;
    url: '/cart/{id}';
};

export type CartControllerAddQuantityErrors = {
    /**
     * Bad request - validation failed
     */
    400: ValidationErrorResponseDto;
    /**
     * Unauthorized - user not authenticated
     */
    401: ErrorResponseDto;
    /**
     * Forbidden - user attempting to update another user's cart item
     */
    403: ErrorResponseDto;
    /**
     * Cart item not found
     */
    404: ErrorResponseDto;
};

export type CartControllerAddQuantityError = CartControllerAddQuantityErrors[keyof CartControllerAddQuantityErrors];

export type CartControllerAddQuantityResponses = {
    /**
     * Quantity updated successfully. Returns complete cart with updated totals.
     */
    200: GetCartResponseDto;
};

export type CartControllerAddQuantityResponse = CartControllerAddQuantityResponses[keyof CartControllerAddQuantityResponses];

export type CartControllerRemoveAllFromCartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cart/all-cart';
};

export type CartControllerRemoveAllFromCartErrors = {
    /**
     * Unauthorized - user not authenticated
     */
    401: ErrorResponseDto;
    /**
     * User not found
     */
    404: ErrorResponseDto;
};

export type CartControllerRemoveAllFromCartError = CartControllerRemoveAllFromCartErrors[keyof CartControllerRemoveAllFromCartErrors];

export type CartControllerRemoveAllFromCartResponses = {
    /**
     * All cart items removed successfully
     */
    200: DeleteCartResponseDto;
};

export type CartControllerRemoveAllFromCartResponse = CartControllerRemoveAllFromCartResponses[keyof CartControllerRemoveAllFromCartResponses];

export type CartControllerBulkAddToCartData = {
    /**
     * Array of products with quantities to add to cart. At least one item is required.
     */
    body: BulkAddCartDto;
    path?: never;
    query?: never;
    url: '/cart/bulk';
};

export type CartControllerBulkAddToCartErrors = {
    /**
     * Bad request - validation failed (empty array, invalid quantities, etc.)
     */
    400: ValidationErrorResponseDto;
    /**
     * Unauthorized - user not authenticated
     */
    401: ErrorResponseDto;
    /**
     * User not found
     */
    404: ErrorResponseDto;
};

export type CartControllerBulkAddToCartError = CartControllerBulkAddToCartErrors[keyof CartControllerBulkAddToCartErrors];

export type CartControllerBulkAddToCartResponses = {
    /**
     * Products processed successfully. Returns added items and any skipped items.
     */
    201: BulkAddCartResponseDto;
};

export type CartControllerBulkAddToCartResponse = CartControllerBulkAddToCartResponses[keyof CartControllerBulkAddToCartResponses];

export type CheckoutControllerGetOrdersData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/checkout/orders/{id}';
};

export type CheckoutControllerGetOrdersResponses = {
    200: unknown;
};

export type CheckoutControllerGetOrderData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/checkout/order/{id}';
};

export type CheckoutControllerGetOrderResponses = {
    200: unknown;
};

export type CheckoutControllerTestMailData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/checkout/test-mail';
};

export type CheckoutControllerTestMailResponses = {
    200: unknown;
};

export type CheckoutControllerConfirmPaymentData = {
    body?: never;
    path: {
        userId: string;
        checkoutId: string;
    };
    query?: never;
    url: '/checkout/confirm-payment/{userId}/{checkoutId}';
};

export type CheckoutControllerConfirmPaymentResponses = {
    200: unknown;
};

export type CheckoutControllerGetTransportationData = {
    body?: never;
    path: {
        id: string;
        location: string;
    };
    query?: never;
    url: '/checkout/{id}/{location}';
};

export type CheckoutControllerGetTransportationResponses = {
    200: unknown;
};

export type CheckoutControllerGetAllOrdersData = {
    body?: never;
    path?: never;
    query: {
        orderStatus: string;
        searchTerm: string;
        page: number;
        paymentStatus: string;
    };
    url: '/checkout/orders';
};

export type CheckoutControllerGetAllOrdersResponses = {
    200: unknown;
};

export type CheckoutControllerInitializeTransactionData = {
    body: InitializeTransaction;
    path: {
        id: string;
    };
    query?: never;
    url: '/checkout/initialize-transaction/{id}';
};

export type CheckoutControllerInitializeTransactionResponses = {
    201: unknown;
};

export type CheckoutControllerOrderStatusData = {
    body: OrderStatus;
    path: {
        id: string;
    };
    query?: never;
    url: '/checkout/order-status/{id}';
};

export type CheckoutControllerOrderStatusResponses = {
    200: unknown;
};

export type CheckoutControllerPaymentStatusData = {
    body: PaymentStatus;
    path: {
        id: string;
    };
    query?: never;
    url: '/checkout/payment-status/{id}';
};

export type CheckoutControllerPaymentStatusResponses = {
    200: unknown;
};

export type CheckoutControllerCancelOrderData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/checkout/cancel-order/{id}';
};

export type CheckoutControllerCancelOrderResponses = {
    200: unknown;
};

export type UploadControllerUploadImageData = {
    body: {
        /**
         * Image file to upload
         */
        image?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/upload/image';
};

export type UploadControllerUploadImageResponses = {
    /**
     * Image uploaded successfully
     */
    201: UploadResponseDto;
};

export type UploadControllerUploadImageResponse = UploadControllerUploadImageResponses[keyof UploadControllerUploadImageResponses];

export type SalesControllerListSalesData = {
    body?: never;
    path?: never;
    query?: {
        status?: 'invoice_requested' | 'pending_payment' | 'paid' | 'packaging' | 'in_transit' | 'delivered';
        customerId?: string;
        page?: number;
        limit?: number;
    };
    url: '/sales';
};

export type SalesControllerListSalesResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type SalesControllerListSalesResponse = SalesControllerListSalesResponses[keyof SalesControllerListSalesResponses];

export type SalesControllerCreateSaleData = {
    body: CreateSaleDto;
    path?: never;
    query?: never;
    url: '/sales';
};

export type SalesControllerCreateSaleResponses = {
    201: Sale;
};

export type SalesControllerCreateSaleResponse = SalesControllerCreateSaleResponses[keyof SalesControllerCreateSaleResponses];

export type SalesControllerCancelSaleData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sales/{id}';
};

export type SalesControllerCancelSaleResponses = {
    200: Sale;
};

export type SalesControllerCancelSaleResponse = SalesControllerCancelSaleResponses[keyof SalesControllerCancelSaleResponses];

export type SalesControllerGetSaleDetailsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sales/{id}';
};

export type SalesControllerGetSaleDetailsResponses = {
    200: Sale;
};

export type SalesControllerGetSaleDetailsResponse = SalesControllerGetSaleDetailsResponses[keyof SalesControllerGetSaleDetailsResponses];

export type SalesControllerUpdateSaleData = {
    body: UpdateSaleDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/sales/{id}';
};

export type SalesControllerUpdateSaleResponses = {
    200: Sale;
};

export type SalesControllerUpdateSaleResponse = SalesControllerUpdateSaleResponses[keyof SalesControllerUpdateSaleResponses];

export type SalesControllerUpdateSaleStatusData = {
    body: UpdateSaleStatusDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/sales/{id}/status';
};

export type SalesControllerUpdateSaleStatusResponses = {
    200: Sale;
};

export type SalesControllerUpdateSaleStatusResponse = SalesControllerUpdateSaleStatusResponses[keyof SalesControllerUpdateSaleStatusResponses];

export type SalesControllerAddLineItemData = {
    body: AddLineItemDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/sales/{id}/line-items';
};

export type SalesControllerAddLineItemResponses = {
    200: Sale;
};

export type SalesControllerAddLineItemResponse = SalesControllerAddLineItemResponses[keyof SalesControllerAddLineItemResponses];

export type SalesControllerAssignBatchesData = {
    body: AssignBatchesDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/sales/{id}/batches';
};

export type SalesControllerAssignBatchesResponses = {
    200: Sale;
};

export type SalesControllerAssignBatchesResponse = SalesControllerAssignBatchesResponses[keyof SalesControllerAssignBatchesResponses];

export type SalesControllerGenerateInvoiceData = {
    body: GenerateInvoiceDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/sales/{id}/invoice';
};

export type SalesControllerGenerateInvoiceResponses = {
    /**
     * Invoice PDF generated successfully
     */
    200: unknown;
};

export type SalesControllerGenerateReceiptData = {
    body: GenerateReceiptDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/sales/{id}/receipt';
};

export type SalesControllerGenerateReceiptResponses = {
    /**
     * Receipt PDF generated successfully
     */
    200: unknown;
};

export type SalesControllerGenerateWaybillData = {
    body: GenerateWaybillDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/sales/{id}/waybill';
};

export type SalesControllerGenerateWaybillResponses = {
    /**
     * Waybill PDF generated successfully
     */
    200: unknown;
};

export type CustomerControllerGetAllCustomersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Items per page
         */
        limit?: number;
    };
    url: '/customers';
};

export type CustomerControllerGetAllCustomersResponses = {
    /**
     * Customers retrieved successfully
     */
    200: unknown;
};

export type CustomerControllerUpdateCustomerData = {
    body: UpdateCustomerDto;
    path?: never;
    query?: never;
    url: '/customers';
};

export type CustomerControllerUpdateCustomerErrors = {
    /**
     * Customer not found
     */
    404: unknown;
    /**
     * Customer with email already exists
     */
    409: unknown;
};

export type CustomerControllerUpdateCustomerResponses = {
    /**
     * Customer updated successfully
     */
    200: unknown;
};

export type CustomerControllerCreateCustomerData = {
    body: CreateCustomerDto;
    path?: never;
    query?: never;
    url: '/customers';
};

export type CustomerControllerCreateCustomerErrors = {
    /**
     * Customer with email already exists
     */
    409: unknown;
};

export type CustomerControllerCreateCustomerResponses = {
    /**
     * Customer created successfully
     */
    201: unknown;
};

export type CustomerControllerDeleteCustomerData = {
    body?: never;
    path: {
        /**
         * Customer ID
         */
        id: string;
    };
    query?: never;
    url: '/customers/{id}';
};

export type CustomerControllerDeleteCustomerErrors = {
    /**
     * Customer not found
     */
    404: unknown;
};

export type CustomerControllerDeleteCustomerResponses = {
    /**
     * Customer deleted successfully
     */
    200: unknown;
};

export type CustomerControllerGetCustomerData = {
    body?: never;
    path: {
        /**
         * Customer ID
         */
        id: string;
    };
    query?: never;
    url: '/customers/{id}';
};

export type CustomerControllerGetCustomerErrors = {
    /**
     * Customer not found
     */
    404: unknown;
};

export type CustomerControllerGetCustomerResponses = {
    /**
     * Customer retrieved successfully
     */
    200: unknown;
};

export type ReportsControllerGetSalesReportData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date for filtering (ISO format)
         */
        fromDate?: string;
        /**
         * End date for filtering (ISO format)
         */
        toDate?: string;
        /**
         * Filter by product ID
         */
        productId?: string;
        /**
         * Filter by product category
         */
        category?: 'Shea Butter' | 'Black Soap' | 'Cosmetics' | 'Shea Soap' | 'Powdered Soap' | 'Dawadawa' | 'Essential Oils' | 'Hair Oil' | 'Grains' | 'Legumes' | 'Other';
        /**
         * Filter by batch ID
         */
        batchId?: string;
        /**
         * Time aggregation level
         */
        aggregation?: 'daily' | 'weekly' | 'monthly' | 'yearly';
        /**
         * Include sales trends
         */
        includeTrends?: boolean;
    };
    url: '/reports/sales';
};

export type ReportsControllerGetSalesReportResponses = {
    /**
     * Sales report generated successfully
     */
    200: unknown;
};

export type ReportsControllerGetSalesByProductData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date for filtering (ISO format)
         */
        fromDate?: string;
        /**
         * End date for filtering (ISO format)
         */
        toDate?: string;
        /**
         * Filter by product ID
         */
        productId?: string;
        /**
         * Filter by product category
         */
        category?: 'Shea Butter' | 'Black Soap' | 'Cosmetics' | 'Shea Soap' | 'Powdered Soap' | 'Dawadawa' | 'Essential Oils' | 'Hair Oil' | 'Grains' | 'Legumes' | 'Other';
        /**
         * Filter by batch ID
         */
        batchId?: string;
        /**
         * Time aggregation level
         */
        aggregation?: 'daily' | 'weekly' | 'monthly' | 'yearly';
    };
    url: '/reports/sales/by-product';
};

export type ReportsControllerGetSalesByProductResponses = {
    /**
     * Product sales report generated successfully
     */
    200: unknown;
};

export type ReportsControllerGetSalesByCategoryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date for filtering (ISO format)
         */
        fromDate?: string;
        /**
         * End date for filtering (ISO format)
         */
        toDate?: string;
        /**
         * Filter by product ID
         */
        productId?: string;
        /**
         * Filter by product category
         */
        category?: 'Shea Butter' | 'Black Soap' | 'Cosmetics' | 'Shea Soap' | 'Powdered Soap' | 'Dawadawa' | 'Essential Oils' | 'Hair Oil' | 'Grains' | 'Legumes' | 'Other';
        /**
         * Filter by batch ID
         */
        batchId?: string;
        /**
         * Time aggregation level
         */
        aggregation?: 'daily' | 'weekly' | 'monthly' | 'yearly';
    };
    url: '/reports/sales/by-category';
};

export type ReportsControllerGetSalesByCategoryResponses = {
    /**
     * Category sales report generated successfully
     */
    200: unknown;
};

export type ReportsControllerGetTopProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date for filtering (ISO format)
         */
        fromDate?: string;
        /**
         * End date for filtering (ISO format)
         */
        toDate?: string;
        /**
         * Filter by product ID
         */
        productId?: string;
        /**
         * Filter by product category
         */
        category?: 'Shea Butter' | 'Black Soap' | 'Cosmetics' | 'Shea Soap' | 'Powdered Soap' | 'Dawadawa' | 'Essential Oils' | 'Hair Oil' | 'Grains' | 'Legumes' | 'Other';
        /**
         * Filter by batch ID
         */
        batchId?: string;
        /**
         * Time aggregation level
         */
        aggregation?: 'daily' | 'weekly' | 'monthly' | 'yearly';
        /**
         * Number of top products to return
         */
        limit?: number;
        sortOrder?: 'ASC' | 'DESC';
    };
    url: '/reports/products/top';
};

export type ReportsControllerGetTopProductsResponses = {
    /**
     * Top products report generated successfully
     */
    200: unknown;
};

export type ReportsControllerGetRevenueDistributionData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date for filtering (ISO format)
         */
        fromDate?: string;
        /**
         * End date for filtering (ISO format)
         */
        toDate?: string;
        /**
         * Filter by product ID
         */
        productId?: string;
        /**
         * Filter by product category
         */
        category?: 'Shea Butter' | 'Black Soap' | 'Cosmetics' | 'Shea Soap' | 'Powdered Soap' | 'Dawadawa' | 'Essential Oils' | 'Hair Oil' | 'Grains' | 'Legumes' | 'Other';
        /**
         * Filter by batch ID
         */
        batchId?: string;
        /**
         * Time aggregation level
         */
        aggregation?: 'daily' | 'weekly' | 'monthly' | 'yearly';
    };
    url: '/reports/products/revenue-distribution';
};

export type ReportsControllerGetRevenueDistributionResponses = {
    /**
     * Revenue distribution report generated successfully
     */
    200: unknown;
};

export type ReportsControllerGetBatchReportData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date for filtering (ISO format)
         */
        fromDate?: string;
        /**
         * End date for filtering (ISO format)
         */
        toDate?: string;
        /**
         * Filter by product ID
         */
        productId?: string;
        /**
         * Filter by product category
         */
        category?: 'Shea Butter' | 'Black Soap' | 'Cosmetics' | 'Shea Soap' | 'Powdered Soap' | 'Dawadawa' | 'Essential Oils' | 'Hair Oil' | 'Grains' | 'Legumes' | 'Other';
        /**
         * Filter by batch ID
         */
        batchId?: string;
        /**
         * Time aggregation level
         */
        aggregation?: 'daily' | 'weekly' | 'monthly' | 'yearly';
    };
    url: '/reports/batches';
};

export type ReportsControllerGetBatchReportResponses = {
    /**
     * Batch report generated successfully
     */
    200: unknown;
};

export type ReportsControllerGetBatchAgingReportData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date for filtering (ISO format)
         */
        fromDate?: string;
        /**
         * End date for filtering (ISO format)
         */
        toDate?: string;
        /**
         * Filter by product ID
         */
        productId?: string;
        /**
         * Filter by product category
         */
        category?: 'Shea Butter' | 'Black Soap' | 'Cosmetics' | 'Shea Soap' | 'Powdered Soap' | 'Dawadawa' | 'Essential Oils' | 'Hair Oil' | 'Grains' | 'Legumes' | 'Other';
        /**
         * Filter by batch ID
         */
        batchId?: string;
        /**
         * Time aggregation level
         */
        aggregation?: 'daily' | 'weekly' | 'monthly' | 'yearly';
    };
    url: '/reports/batches/aging';
};

export type ReportsControllerGetBatchAgingReportResponses = {
    /**
     * Batch aging report generated successfully
     */
    200: unknown;
};

export type ReportsControllerGetInventoryReportData = {
    body?: never;
    path?: never;
    query?: {
        category?: 'Shea Butter' | 'Black Soap' | 'Cosmetics' | 'Shea Soap' | 'Powdered Soap' | 'Dawadawa' | 'Essential Oils' | 'Hair Oil' | 'Grains' | 'Legumes' | 'Other';
        /**
         * Filter by product ID
         */
        productId?: string;
        /**
         * Show only low stock items
         */
        lowStockOnly?: boolean;
        /**
         * Low stock threshold
         */
        lowStockThreshold?: number;
    };
    url: '/reports/inventory';
};

export type ReportsControllerGetInventoryReportResponses = {
    /**
     * Inventory report generated successfully
     */
    200: unknown;
};

export type ReportsControllerGetStockMovementReportData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date for filtering (ISO format)
         */
        fromDate?: string;
        /**
         * End date for filtering (ISO format)
         */
        toDate?: string;
        /**
         * Filter by product ID
         */
        productId?: string;
        /**
         * Filter by product category
         */
        category?: 'Shea Butter' | 'Black Soap' | 'Cosmetics' | 'Shea Soap' | 'Powdered Soap' | 'Dawadawa' | 'Essential Oils' | 'Hair Oil' | 'Grains' | 'Legumes' | 'Other';
        /**
         * Filter by batch ID
         */
        batchId?: string;
        /**
         * Time aggregation level
         */
        aggregation?: 'daily' | 'weekly' | 'monthly' | 'yearly';
    };
    url: '/reports/stock-movement';
};

export type ReportsControllerGetStockMovementReportResponses = {
    /**
     * Stock movement report generated successfully
     */
    200: unknown;
};

export type ReportsControllerGetComparativeReportData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Start date for current period
         */
        currentFromDate: string;
        /**
         * End date for current period
         */
        currentToDate: string;
        /**
         * Start date for previous period
         */
        previousFromDate: string;
        /**
         * End date for previous period
         */
        previousToDate: string;
        category?: 'Shea Butter' | 'Black Soap' | 'Cosmetics' | 'Shea Soap' | 'Powdered Soap' | 'Dawadawa' | 'Essential Oils' | 'Hair Oil' | 'Grains' | 'Legumes' | 'Other';
    };
    url: '/reports/comparative';
};

export type ReportsControllerGetComparativeReportResponses = {
    /**
     * Comparative report generated successfully
     */
    200: unknown;
};

export type ReportsControllerGetDashboardSummaryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date for filtering (ISO format)
         */
        fromDate?: string;
        /**
         * End date for filtering (ISO format)
         */
        toDate?: string;
        /**
         * Filter by product ID
         */
        productId?: string;
        /**
         * Filter by product category
         */
        category?: 'Shea Butter' | 'Black Soap' | 'Cosmetics' | 'Shea Soap' | 'Powdered Soap' | 'Dawadawa' | 'Essential Oils' | 'Hair Oil' | 'Grains' | 'Legumes' | 'Other';
        /**
         * Filter by batch ID
         */
        batchId?: string;
        /**
         * Time aggregation level
         */
        aggregation?: 'daily' | 'weekly' | 'monthly' | 'yearly';
    };
    url: '/reports/dashboard-summary';
};

export type ReportsControllerGetDashboardSummaryResponses = {
    /**
     * Dashboard summary generated successfully
     */
    200: unknown;
};

export type DashboardControllerGetSummaryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start date for period filtering (ISO format)
         */
        fromDate?: string;
        /**
         * End date for period filtering (ISO format)
         */
        toDate?: string;
        /**
         * Include comparison with previous period
         */
        includeComparison?: boolean;
    };
    url: '/dashboard/summary';
};

export type DashboardControllerGetSummaryResponses = {
    /**
     * Dashboard summary retrieved successfully
     */
    200: unknown;
};

export type DashboardControllerGetTrendsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Period for trend data
         */
        period?: '7' | '30' | '90';
    };
    url: '/dashboard/trends';
};

export type DashboardControllerGetTrendsResponses = {
    /**
     * Dashboard trends retrieved successfully
     */
    200: unknown;
};

export type DashboardControllerGetHighlightsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of top/bottom products to return
         */
        limit?: number;
    };
    url: '/dashboard/highlights';
};

export type DashboardControllerGetHighlightsResponses = {
    /**
     * Dashboard highlights retrieved successfully
     */
    200: unknown;
};

export type DashboardControllerGetAlertsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Low stock threshold
         */
        lowStockThreshold?: number;
        /**
         * Days until expiry for critical alert
         */
        expiryWarningDays?: number;
    };
    url: '/dashboard/alerts';
};

export type DashboardControllerGetAlertsResponses = {
    /**
     * Dashboard alerts retrieved successfully
     */
    200: unknown;
};

export type DashboardControllerGetActivityData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of recent items to return
         */
        limit?: number;
    };
    url: '/dashboard/activity';
};

export type DashboardControllerGetActivityResponses = {
    /**
     * Dashboard activity retrieved successfully
     */
    200: unknown;
};

export type ProfileControllerGetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me/profile';
};

export type ProfileControllerGetProfileErrors = {
    /**
     * Unauthorized - not logged in
     */
    401: unknown;
};

export type ProfileControllerGetProfileResponses = {
    /**
     * Profile retrieved successfully
     */
    200: ProfileResponseDto;
};

export type ProfileControllerGetProfileResponse = ProfileControllerGetProfileResponses[keyof ProfileControllerGetProfileResponses];

export type ProfileControllerUpdateProfileData = {
    body: UpdateProfileDto;
    path?: never;
    query?: never;
    url: '/me/profile';
};

export type ProfileControllerUpdateProfileErrors = {
    /**
     * Bad request - validation failed
     */
    400: unknown;
    /**
     * Unauthorized - not logged in
     */
    401: unknown;
    /**
     * Email already in use by another account
     */
    409: unknown;
};

export type ProfileControllerUpdateProfileResponses = {
    /**
     * Profile updated successfully
     */
    200: ProfileResponseDto;
};

export type ProfileControllerUpdateProfileResponse = ProfileControllerUpdateProfileResponses[keyof ProfileControllerUpdateProfileResponses];

export type ProfileControllerUploadAvatarData = {
    body: {
        /**
         * Avatar image file
         */
        file?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/me/profile/avatar';
};

export type ProfileControllerUploadAvatarErrors = {
    /**
     * Bad request - invalid file type or size
     */
    400: unknown;
    /**
     * Unauthorized - not logged in
     */
    401: unknown;
};

export type ProfileControllerUploadAvatarResponses = {
    /**
     * Avatar uploaded successfully
     */
    200: unknown;
};

export type ContactControllerSubmitContactFormData = {
    body: ContactUsDto;
    path?: never;
    query?: never;
    url: '/contact';
};

export type ContactControllerSubmitContactFormErrors = {
    /**
     * Validation error - Invalid input
     */
    400: ContactUsErrorResponseDto;
    /**
     * Server error - Unable to process request
     */
    500: ContactUsErrorResponseDto;
};

export type ContactControllerSubmitContactFormError = ContactControllerSubmitContactFormErrors[keyof ContactControllerSubmitContactFormErrors];

export type ContactControllerSubmitContactFormResponses = {
    /**
     * Message sent successfully
     */
    200: ContactUsSuccessResponseDto;
};

export type ContactControllerSubmitContactFormResponse = ContactControllerSubmitContactFormResponses[keyof ContactControllerSubmitContactFormResponses];
