const items = {
    "Shea butter": [
      {
        id: 1,
        imageSrc: "shea butter-white.jpg",
        title: "Yellow Shea butter",
        content: "1 kg",
        price: "22",
        price_retail: "25",
        rating: "5.0",
        reviews: "87",
        url: "#",
      },
      {
        id: 2,
        imageSrc: "organic shea butter.jpg",
        title: "Shea butter pomade",
        content: "Small size",
        price: "5",
        price_retail: "6",
        rating: "4.8",
        reviews: "32",
        url: "#",
      },
      {
        id: 3,
        imageSrc: "shea butter.jpg",
        title: "Shea butter pomade",
        content: "Big size",
        price: "15",
        price_retail: "20",
        rating: "4.9",
        reviews: "89",
        url: "#",
      },
      {
        id: 4,
        imageSrc: "hairfood.jpeg",
        title: "Hair Food",
        content: "Big size",
        price: "20",
        price_retail: "25",
        rating: "4.6",
        reviews: "12",
        url: "#",
      },
      {
        imageSrc: "hair food-white.jpg",
        title: "Hair Food",
        content: "Small size",
        price: "9",
        price_retail: "10",
        rating: "100",
        reviews: "19",
        url: "#",
      },
      {
        imageSrc: "malti baby shea-white.jpg",
        title: "Pomade for babies",
        content: "fragrance free",
        price: "15",
        price_retail: "20",
        rating: "20",
        reviews: "61",
        url: "#",
      },
      {
        imageSrc: "shea-white.jpeg",
        title: "Shea butter",
        content: "1kg",
        price: "22",
        price_retail: "25",
        rating: "25",
        reviews: "95",
        url: "#",
      },
      {
        imageSrc: "foot cream.jpg",
        title: "Shea butter foot cream",
        content: "Nourishes your feet",
        price: "5",
        price_retail: "6",
        rating: "61",
        reviews: "26",
        url: "#",
      },
    ],
    Soap: [
      {
        imageSrc: "black soap2-white.jpg",
        title: "Container Black Soap",
        content: "Compressed",
        price: "22",
        price_retail: "25",
        rating: "5.0",
        reviews: "87",
        url: "#",
      },
      {
        imageSrc: "black soap-white.jpg",
        title: "Black Soap",
        content: "Moulded",
        price: "7",
        price_retail: "8",
        rating: "4.8",
        reviews: "32",
        url: "#",
      },
      {
        imageSrc: "liquid soap.jpg",
        title: "Liquid Soap",
        content: "Lotion soap",
        price: "22",
        price_retail: "25",
        rating: "4.9",
        reviews: "89",
        url: "#",
      },
    ],
    "Essential Oils": [
      {
        imageSrc: "baobab oil2-white.jpg",
        title: "Baobab Oil",
        content: "250 ml",
        price: "20",
        price_retail: "25",
        rating: "5.0",
        reviews: "87",
        url: "#",
      },
      {
        imageSrc: "hair oil.jpg",
        title: "Hair Oil",
        content: "250 ml",
        price: "20",
        price_retail: "25",
        rating: "4.8",
        reviews: "32",
        url: "#",
      },
      {
        imageSrc: "Kapok oil.jpg",
        title: "Kapok Oil",
        content: "250 ml",
        price: "25",
        price_retail: "30",
        rating: "4.9",
        reviews: "89",
        url: "#",
      },
      {
        imageSrc: "Moringa oil.jpg",
        title: "Moringa Oil seed extract",
        content: "1 liter",
        price: "300",
        price_retail: "310",
        rating: "4.6",
        reviews: "12",
        url: "#",
      },
      {
        imageSrc: "Moringa oil-white.jpg",
        title: "Moringa Oil seed extract",
        content: "250ml",
        price: "75",
        price_retail: "80",
        rating: "100",
        reviews: "19",
        url: "#",
      },
      {
        imageSrc: "neem oil.jpg",
        title: "Neem oil",
        content: "250ml",
        price: "20",
        price_retail: "25",
        rating: "20",
        reviews: "61",
        url: "#",
      },
      {
        imageSrc: "shea oil2-white.jpg",
        title: "Shea oil",
        content: "250ml",
        price: "20",
        price_retail: "25",
        rating: "25",
        reviews: "95",
        url: "#",
      },
      {
        imageSrc: "shea oil-white.jpg",
        title: "Shea Oil",
        content: "1 liter",
        price: "42",
        price_retail: "45",
        rating: "61",
        reviews: "26",
        url: "#",
      },
      {
        imageSrc: "virgin oil.jpg",
        title: "Virgin Cocoanut Oil",
        content: "250ml",
        price: "20",
        price_retail: "25",
        rating: "61",
        reviews: "26",
        url: "#",
      },
    ],
    Others: [
      {
        imageSrc: "dawadawa tea.jpg",
        title: "Dawadawa tea",
        content: "Big size",
        price: "18",
        price_retail: "20",
        rating: "5.0",
        reviews: "87",
        url: "#",
      },
      {
        imageSrc: "dawadawa powder.jpg",
        title: "Dawadawa spices",
        content: "Specially made",
        price: "9",
        price_retail: "10",
        rating: "4.8",
        reviews: "32",
        url: "#",
      },
      {
        imageSrc: "ginger powder.jpg",
        title: "Ginger Poweder",
        content: "Specially made",
        price: "10",
        price_retail: "12",
        rating: "4.9",
        reviews: "89",
        url: "#",
      },
      {
        imageSrc: "pepper powder.jpg",
        title: "Pepper powder",
        content: "Specially made",
        price: "300",
        price_retail: "310",
        rating: "4.6",
        reviews: "12",
        url: "#",
      },
      {
        imageSrc: "tumeric powder.jpg",
        title: "Tumeric Powder",
        content: "Special",
        price: "18",
        price_retail: "20",
        rating: "100",
        reviews: "19",
        url: "#",
      },
      {
        imageSrc: "honey.jpeg",
        title: "Honey",
        content: "500ml",
        price: "22",
        price_retail: "25",
        rating: "20",
        reviews: "61",
        url: "#",
      },
    ],
    // Others: getRandomCards()
  }
  export default items;